[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
secp256k1_multisig = "FELadcrJKJ6MuDZPRb4Q2vcY82MnkZQ5WdqVH8Mv2Wcd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
