name: Anchor Test

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_CLI_VERSION: 2.0.25
  NODE_VERSION: 18.14.2
  ANCHOR_CLI_VERSION: 0.30.1

jobs:
  cli_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
      - name: Run Anchor Tests
        run: |
          cd tokens
          anchor test
        shell: bash